version: 1.0.{build}

environment:
  access_token:
    secure: 4L8MS6vjIHzShfn4kfiesuBNu9Ojv6Vl4TtQFt0JZGaiMloLkHq86xzONq29mzkN

pull_requests:
  do_not_increment_build_number: false

image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

branches:
  except:
    - gh-pages

before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            choco install docfx -y
        }

dotnet_csproj:
  patch: true
  file: PTIRelianceLib\PTIRelianceLib.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

build_script:
  - ps: .\tools\build_project.ps1

test_script:
  - ps: .\tools\run_tests.ps1

artifacts:
  - path: **\*.nupkg

on_success:
  - ps: >-
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            .\tools\deploy_docs.ps1
        }
