#region Header
// IPyramidDevice.cs
// PTIRelianceLib
// Cory Todd
// 16-05-2018
// 7:11 AM
#endregion

namespace PTIRelianceLib
{
    /// <summary>
    /// Common return codes generated by this library
    /// </summary>
    public enum ReturnCodes
    {
        /// <summary>
        /// Operation completed normally, printer is online and ready for work
        /// </summary>
        Okay,
        /// <summary>
        /// Operation was started with the target but the response code
        /// from the target indicates failure.
        /// </summary>
        ExecutionFailure,
        /// <summary>
        /// No <see cref="IPyramidDevice"/> is connected to the system
        /// </summary>
        DeviceNotConnected,
        /// <summary>
        /// The format of the request is invalid
        /// </summary>
        InvalidRequest,
        /// <summary>
        /// The request is known but the payload is malformed
        /// </summary>
        InvalidRequestPayload,
        /// <summary>
        /// The target was communicating normally and then unexpectedly stopped
        /// </summary>
        TargetStoppedResponding,
        /// <summary>
        /// The target device has firmware that is not compatible with this library
        /// </summary>
        FlashInstalledFwNotSupported,
        /// <summary>
        /// The specified firmware file is corrupt
        /// </summary>
        FlashFileInvalid,
        /// <summary>
        /// The target printer is denying your update request
        /// </summary>
        FlashPermissionDenied,
        /// <summary>
        /// The flash operation completed but the checksum is incorrect. Try
        /// flash updating again.
        /// </summary>
        FlashChecksumMismatch,
        /// <summary>
        /// The specified configuration file is invalid. Use Reliance Tools
        /// to generate a valid configuration.
        /// </summary>
        ConfigFileInvalid,
        /// <summary>
        /// Operation was aborted by library due to sanity check failure
        /// </summary>
        OperationAborted
    }
}
